{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "kubernetes-hpa-custom.fullname" . }}
  namespace: {{ include "kubernetes-hpa-custom.namespace" . }}
  labels:
    {{ include "kubernetes-hpa-custom.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ toYaml .Values.ingress.annotations | nindent 4}}
  {{ end -}}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .name }} 
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
  {{ end -}}
{{ end -}}
