language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - ./.m2

services:
  - docker

env:
  - SETTINGS_PATH=settings.xml

before_install:
  - mvn compile -B -s ${SETTINGS_PATH} -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true

notifications:
  wekhooks: https://hooks.slack.com/services/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
  email: false