language: java

jdk:
  - oraclejdk8

stages:
  - name: compile
  - name: tests
  - name: quality-code
  - name: build
  - name: snapshot
    if: branch != master
  - name: release
    if: branch = master
  - name: deploy
  - name: deploy-verify

cache:
  directories:
    - $HOME/.m2

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

env:
  - SETTINGS_PATH=settings.xml
  - CONTAINER_REPOSITORY_URL=006223355744.dkr.ecr.us-east-1.amazonaws.com
  - IMAGE_NAME=kubernetes-hpa-custom

jobs:
  include:
    - stage: compile
      script:
        - mvn compile -B

    - stage: tests
      services:
        - rabbitmq
        - postgresql
      before_script:
        - psql -c "CREATE USER database_development WITH PASSWORD '123456' NOCREATEDB;" -U postgres
        - psql -c "CREATE DATABASE database_development OWNER database_development;" -U postgres
      script:
        - mvn verify -B

    - stage: quality-code
      script:
        - mvn sonar:sonar -Dsonar.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_LOGIN} -Dsonar.password=${SONARQUBE_PASSWORD} -B

    - stage: build
      services:
        - docker
      script:
        - mvn clean package -B -DskipTests -s ${SETTINGS_PATH}
      before_deploy:
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then TAG=latest; fi;
        - TAG=$(echo "$TRAVIS_BRANCH" | sed 's/\//\-/g')
        - $(aws ecr get-login --no-include-email --region us-east-1)
      deploy:
        - docker build -f docker/Dockerfile -t ${CONTAINER_REPOSITORY_URL}/${IMAGE_NAME}:${TAG} .
        - docker push ${CONTAINER_REPOSITORY_URL}/${IMAGE_NAME}:${TAG}

    - stage: snapshot
      script:
         - mvn deploy -B -DskipTests -Dartifactory.url=${ARTIFACTORY_URL} -Drelease.scm.user=${RELEASE_SCM_USER} -Drelease.scm.token=${RELEASE_SCM_TOKEN}

    - stage: release
      before_script:
        - git config --global user.email "ci@atech.com.br"
        - git config --global user.name "CI Atech Release"
        - git checkout ${TRAVIS_BRANCH}
        - git reset --hard origin/${TRAVIS_BRANCH}
      script:
        - mvn release:clean release:prepare release:perform -B -DscmCommentPrefix="[maven-release] [skip ci] " -Darguments="-DskipTests -Dartifactory.url=${ARTIFACTORY_URL}"

notifications:
  webhooks: https://hooks.slack.com/services/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
  email: false