server.port: 8080

spring:
  application.name: kubernetes-hpa-custom
  profiles.active: ${PROFILE:local}

management:
  metrics:
    tags:
      application: ${spring.application.name}
      application-uuid: ${spring.application.name}:${random.uuid}
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]
  endpoint:
    health:
      show-details: ALWAYS