version: '2'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    mem_limit: 150m
    networks:
      - development-network

  postgres:
    image: healthcheck/postgres
    container_name: postgres
    volumes:
      - ./assets/postgres/initdb/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    mem_limit: 150m
    networks:
      - development-network

networks:
  development-network:
    external: true