version: 0.2

env:
  variables:
    SETTINGS_PATH: settings.xml
    SONARQUBE_URL: https://sonar-b2b.atech.com.br/sonarqube
    ARTIFACTORY_URL: https://artifactory-b2b.atech.com.br/artifactory
    CI_COMMIT_REF_NAME: master
  parameter-store:
    SSH_KEY: "prod-ssh-key"
    SONARQUBE_LOGIN: "prod-sonarqube-login"
    SONARQUBE_PASSWORD: "prod-sonarqube-password"
    RELEASE_SCM_USER: "prod-release-scm-user"
    RELEASE_SCM_TOKEN: "prod-release-scm-token"

phases:

  install:
    commands:
      - echo Entered the install phase and compile dependencies from project on `date`...
      - mvn -B compile -s ${SETTINGS_PATH}

  pre_build:
    commands:
      - echo Pre-build started and running tests from project on `date`...
      - mvn -B verify -s ${SETTINGS_PATH}

  build:
    commands:
      - echo Build started and generating fat-jar from project on `date`...
      - mvn clean package -B -s ${SETTINGS_PATH} -DskipTests
    finally:
      - echo Generating quality code on sonarqube...
      - mvn sonar:sonar -Dsonar.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_LOGIN} -Dsonar.password=${SONARQUBE_PASSWORD} -B -s ${SETTINGS_PATH}

  post_build:
    commands:
      - echo Entered the Post-Build phase and generating release artifact to jFrog on `date`...
      - echo ${SSH_KEY} > ~/.ssh/id_rsa
      - git config --global user.email "ci-boot@alveesrenan-dev.com.br"
      - git config --global user.name "CI BootRobot Release"
      - git checkout ${CI_COMMIT_REF_NAME}
      - git reset --hard origin/${CI_COMMIT_REF_NAME}
    finally:
      - mvn release:clean release:prepare release:perform -B -DscmCommentPrefix="[maven-release] [skip ci] " -Darguments="-DskipTests -Dartifactory.url=${ARTIFACTORY_URL}" -Drelease.scm.user=${RELEASE_SCM_USER} -Drelease.scm.token=${RELEASE_SCM_TOKEN} -s ${SETTINGS_PATH}

artifacts:
  files:
    - target/kubernetes-hpa-custom.jar
  discard-paths: yes

cache:
  paths:
    - './.m2'