version: 0.2

env:
  variables:
    PROJECT_NAME: kubernetes-hpa-custom
    REPOSITORY_URI: 006223355744.dkr.ecr.us-east-1.amazonaws.com/kubernetes-hpa-custom
    IMAGE_TAG: latest

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)

  build:
    commands:
      - echo Build started and building Docker image on `date`
      - docker build --build-arg JAR_FILE=kubernetes-hpa-custom.jar -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Post Build started and generating new task definition on `date`
      - aws ecs register-task-definition --region us-east-1 --cli-input-json file://task-definition.json