version: 0.2

env:
  variables:
    PROJECT_NAME: kubernetes-hpa-custom
    REPOSITORY_URI: 006223355744.dkr.ecr.us-east-1.amazonaws.com/kubernetes-hpa-custom
    IMAGE_TAG: latest

phases:

  pre_build:
    commands:
      - echo Installing some packages to run on this build step on `date`
      - apt-get install -y jq yq

  build:
    commands:
      - echo Build started and building Docker image on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - docker build --build-arg JAR_FILE=kubernetes-hpa-custom.jar -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - touch image-version.txt && echo ${IMAGE_NAME}:${TAG} > image-version.txt

  post_build:
    commands:
      - echo Post Build started and generating new task definition on `date`
      - IMAGE_VERSION=$(cat image-version.txt)
      - TASK_DEFINITION=$(jq '.containerDefinitions[0].image = $IMAGE_VERSION' --arg IMAGE_VERSION $IMAGE_VERSION task-definition.json)
      - echo $TASK_DEFINITION > task-definition.json
      - Generating new version of task-definition.json file to ECS on `date`
      - TASK_DEFINITION_ARN=$(aws ecs register-task-definition --region us-east-1 --cli-input-json file://task-definition.json | jq '.taskDefinition.taskDefinitionArn')
      - echo Generating new version of appspec.yml to CodeDeploy on `date`
      - echo $(jq '.Resources[0].TargetService.Properties.TaskDefinition = $TASK_DEFINITION_ARN' --arg TASK_DEFINITION_ARN $TASK_DEFINITION_ARN appspec.json) > appspec.json

artifacts:
  files:
    - appspec.json
  discard-paths: yes