nameOverride: "kubernetes-hpa-custom"
fullnameOverride: "kubernetes-hpa-custom"

replicaCount: 1

application:
  name: kubernetes-hpa-custom
  component_type: microservice

image:
  repository: renaalve/kubernetes-hpa-custom
  tag: latest
  pullPolicy: Always
  pullSecrets: hub.docker.com

deployment:
  name: kubernetes-hpa-custom
  containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: http

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - name: app1.alveesrenan.com
      path: /
      serviceName: kubernetes-hpa-custom
      servicePort: 80

hpa:
  enabled: false
  annotations: {}
  minReplicas: 1
  maxReplicas: 10
  metrics:
    targetCpuAverageUtilization: 50
    targetMemoryAverageUtilization: 80