server.port: 8080

spring:
  application.name: kubernetes-hpa-custom
  profiles.active: ${PROFILE:local}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

management:
  metrics:
    tags:
      application: ${spring.application.name}:${random.uuid}
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]

amqp:
  queue:
    name: kubernetes-hpa-queue
    exchange: kubernetes-hpa-exchange
    routingKey: kubernetes-hpa