apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-hpa-custom
spec:
  selector:
    matchLabels:
      app: kubernetes-hpa-custom
  template:
    metadata:
      labels:
        app: kubernetes-hpa-custom
    spec:
      containers:
        - name: kubernetes-hpa-custom
          image: renaalve/kubernetes-hpa-custom
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          env:
            - name: PROFILE
              value: prod
            - name: RABBITMQ_HOST
              value: rabbitmq.monitoring
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
          resources:
            limits:
              memory: 256Mi
      restartPolicy: Always
      imagePullSecrets:
        - name: hub.docker.com

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-hpa-custom
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: kubernetes-hpa-custom
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

#---
#
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: kubernetes-hpa-custom
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: kubernetes-hpa-custom
#  minReplicas: 1
#  maxReplicas: 3
#  metrics:
#    - type: External
#      external:
#        metricName: kubernetes_hpa_queue_messages_available
#        targetValue: 3